### ISSUE TITLE
unable to find shortcut

### ISSUE THREAD

**Issue by JoeggiCH** [cmdvmd/common-clipboard#5]
Hi

Thanks for preparing this ! Might be very handy :-)

When accessing https://routinehub.co/shortcut/16222/ the browser is redirected to : https://www.icloud.com/shortcuts/844d944db8254ca096ab28b2df37d320
and icloud shows "Not Found Unable to find the shortcut."

Any help appreciated!
Joerg

**Comment by cmdvmd** [comment]
Thank you so much for your interest in this project! I don't have any problems accessing the link on my end. Maybe try restarting your device and scanning the qr code again?

**Comment by JoeggiCH** [comment]
Yep, works again. Must have been a temporary issue.
Thanks Vishal!
